# Generated by Django 6.0.6 on 2026-06-16 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('carrier_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('reliability', models.FloatField(default=1.0)),
                ('sustainability', models.FloatField(default=0.8)),
                ('base_rate_per_mile', models.FloatField(default=1.5)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=20)),
                ('current_tick', models.IntegerField(default=0)),
                ('total_ticks', models.IntegerField(default=48)),
                ('total_cost', models.FloatField(default=0.0)),
                ('sla_compliance', models.FloatField(default=1.0)),
                ('emissions', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('ASSIGNED', 'Assigned to Carrier'), ('IN_TRANSIT', 'In Transit'), ('DELAYED', 'Delayed'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('weight', models.FloatField()),
                ('cost', models.FloatField(default=0.0)),
                ('eta_ticks', models.IntegerField(default=0)),
                ('deadline_ticks', models.IntegerField(default=100)),
                ('route_mileage', models.FloatField(default=0.0)),
                ('current_position_progress', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='DisruptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField()),
                ('event_type', models.CharField(choices=[('TRUCK_BREAKDOWN', 'Truck Breakdown'), ('WEATHER_DELAY', 'Severe Weather Delay'), ('RUSH_ORDER', 'Sudden High Priority Order'), ('CARRIER_CANCELLATION', 'Carrier Cancellation')], max_length=30)),
                ('target_shipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at_tick', models.IntegerField(blank=True, null=True)),
                ('resolution_details', models.TextField(blank=True, null=True)),
                ('simulation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logistics.simulationrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField()),
                ('thought', models.TextField()),
                ('action', models.CharField(max_length=100)),
                ('action_input', models.TextField()),
                ('observation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logistics.simulationrun')),
            ],
        ),
    ]
